export const Config = {
  CANVAS_WIDTH: 800,
  CANVAS_HEIGHT: 600,
  COLUMNS: 12,
  LETTER_TRAVEL_TIME_MS: 5000,
  SPAWN_RATE_PER_SEC: 5,
  STARTING_TIME_SEC: 30,
  TURN_TIME_SEC: 15,
  LOW_TIME_THRESHOLD_SEC: 3,
  FONT_FAMILY: '600 28px sans-serif',
  LETTER_STYLE: '#e5e7eb',
  VOWEL_STYLE: '#facc15',
  BG_COLOR: '#0f172a',
  LETTER_FREQ_MODE: 'uniform'
};

